-- 1. WHAT WAS THE TOTAL REVENUE GENERATED LAST YEAR, AND HOW MANY ORDERS DID WE PROCESS?
SELECT 
    YEAR(INVOICEDATE) AS YEAR,
    SUM(REVENUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT INVOICENO) AS TOTAL_ORDERS
FROM ONLINE_RETAIL
WHERE YEAR(INVOICEDATE) = 2010
GROUP BY YEAR(INVOICEDATE);



-- 2. WHICH 10 PRODUCTS GENERATED THE HIGHEST REVENUE, AND HOW MUCH REVENUE DID EACH CONTRIBUTE?
WITH CATEGORY_WITH_REVENUE AS(
SELECT 
    DESCRIPTION AS PRODUCT_NAME,
    ROUND(SUM(REVENUE),2) AS TOTAL_REVENUE,
    DENSE_RANK() OVER( ORDER BY SUM(REVENUE) DESC) AS RANKING
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION)

SELECT PRODUCT_NAME,
TOTAL_REVENUE,
RANKING
FROM CATEGORY_WITH_REVENUE
WHERE RANKING <= 10;



-- 3. WHICH PRODUCTS ARE SELLING THE MOST IN TERMS OF QUANTITY, AND DO THEY ALSO GENERATE HIGH REVENUE?
SELECT 
    DESCRIPTION AS PRODUCT_NAME,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(REVENUE) AS TOTAL_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(QUANTITY) DESC) AS RANKING_ON_QUANTITY,
    DENSE_RANK() OVER(ORDER BY SUM(REVENUE) DESC) AS RANKING_ON_REVENUE
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION;



-- 4. ARE THERE PRODUCTS THAT SELL FREQUENTLY BUT GENERATE VERY LITTLE REVENUE?
SELECT 
    DESCRIPTION AS PRODUCT_NAME,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(REVENUE) AS TOTAL_REVENUE,
    SUM(REVENUE) / SUM(QUANTITY) AS REVENUE_PER_ITEM
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION
HAVING 
    SUM(QUANTITY) > 100
AND 
    SUM(REVENUE) / SUM(QUANTITY) < 2
ORDER BY TOTAL_QUANTITY DESC;




-- 5. WHICH CUSTOMERS ARE OUR TOP SPENDERS, AND HOW MUCH REVENUE DID EACH OF THEM GENERATE?
WITH CUSTOMER_REVENUE AS (
SELECT
    CUSTOMERID,
    SUM(REVENUE) AS TOTAL_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(REVENUE) DESC) AS REVENUE_RANK
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
)

SELECT
    CUSTOMERID,
    TOTAL_REVENUE,
    REVENUE_RANK
FROM CUSTOMER_REVENUE
WHERE REVENUE_RANK <= 10;



-- 6. WHAT PERCENTAGE OF OUR TOTAL REVENUE COMES FROM THE TOP 10 CUSTOMERS?
WITH CUSTOMER_RANKING AS(
SELECT 
    CUSTOMERID,
    SUM(REVENUE) AS TOTAL_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(REVENUE) DESC) AS RANKING
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
)
    

SELECT
ROUND(
        100.0 * SUM(TOTAL_REVENUE) /
        (SELECT SUM(REVENUE) FROM ONLINE_RETAIL),
        2
    ) AS TOP10_REVENUE_PERCENTAGE
FROM CUSTOMER_RANKING
WHERE RANKING <= 10;




-- 7. HOW MANY UNIQUE CUSTOMERS HAVE MADE PURCHASES IN OUR STORE?
SELECT COUNT(DISTINCT CUSTOMERID) FROM ONLINE_RETAIL;




-- 8. WHICH CUSTOMERS PLACED THE HIGHEST NUMBER OF ORDERS, REGARDLESS OF HOW MUCH THEY SPENT?
SELECT * 
FROM(
    SELECT
    CUSTOMERID,
    COUNT(DISTINCT INVOICENO) AS TOTAL_ORDER_PLACED,
    DENSE_RANK() OVER(ORDER BY COUNT(INVOICENO) DESC) AS MOST_ORDER_RANKING
    FROM ONLINE_RETAIL
    GROUP BY CUSTOMERID) T
WHERE MOST_ORDER_RANKING <= 20;




-- 9. ARE THERE CUSTOMERS WHO MADE ONLY ONE PURCHASE AND NEVER RETURNED?
SELECT 
    CUSTOMERID, 
    COUNT(DISTINCT INVOICENO) AS TOTAL_ORDER_PLACED
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
HAVING COUNT(DISTINCT INVOICENO) = 1;




-- 10. WHICH COUNTRIES GENERATE THE MOST REVENUE, AND HOW MANY CUSTOMERS COME FROM EACH OF THOSE COUNTRIES?
SELECT 
    COUNTRY,
    SUM(REVENUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT CUSTOMERID) AS TOTAL_CUSTOMERS
FROM ONLINE_RETAIL
GROUP BY COUNTRY
ORDER BY TOTAL_REVENUE DESC;





-- 11. WHICH COUNTRIES HAVE MANY CUSTOMERS BUT RELATIVELY LOW REVENUE PER CUSTOMER?
SELECT 
    COUNTRY,
    COUNT(DISTINCT CUSTOMERID) AS TOTAL_CUSTOMERS,
    SUM(REVENUE) AS TOTAL_REVENUE,
    ROUND(SUM(REVENUE) / COUNT(DISTINCT CUSTOMERID),2) AS REVENUE_PER_CUSTOMER
FROM ONLINE_RETAIL
GROUP BY COUNTRY
HAVING 
    COUNT(DISTINCT CUSTOMERID) > 50
    AND
    SUM(REVENUE) / COUNT(DISTINCT CUSTOMERID) < 2000
ORDER BY REVENUE_PER_CUSTOMER;




-- 12. WHAT IS THE AVERAGE ORDER VALUE ACROSS ALL ORDERS?
SELECT
    SUM(REVENUE)/ COUNT(DISTINCT INVOICENO) AS AVERAGE_ORDERS
FROM ONLINE_RETAIL;




-- 13. WHICH INDIVIDUAL ORDERS GENERATED THE HIGHEST REVENUE, AND WHO PLACED THEM?
SELECT
    INVOICENO,
    CUSTOMERID,
    SUM(REVENUE)  AS TOTAL_REVENUE
FROM ONLINE_RETAIL
GROUP BY INVOICENO, CUSTOMERID
ORDER BY TOTAL_REVENUE DESC;




-- 14. WHICH MONTH GENERATED THE HIGHEST REVENUE, AND HOW DOES REVENUE CHANGE ACROSS MONTHS?
SELECT
    FORMAT(INVOICEDATE,'yyyy-MM') AS MONTHS,
    Round(SUM(REVENUE),2) AS TOTAL_REVENUE
FROM ONLINE_RETAIL
GROUP BY FORMAT(INVOICEDATE,'yyyy-MM')
ORDER BY FORMAT(INVOICEDATE,'yyyy-MM');




-- 15. ON WHICH DAY OF THE WEEK DO CUSTOMERS PLACE THE MOST ORDERS?
SELECT
    DATEPART(DW, INVOICEDATE) AS WEEK_DAY,
    COUNT(DISTINCT INVOICENO) AS NUMBERS_OF_ORDERS
FROM ONLINE_RETAIL
GROUP BY DATEPART(DW, INVOICEDATE)
ORDER BY COUNT(DISTINCT INVOICENO) DESC;




-- 16. WHAT IS THE AVERAGE NUMBER OF PRODUCTS CUSTOMERS PURCHASE PER ORDER?
SELECT
    SUM(QUANTITY) * 1.0 / COUNT(DISTINCT INVOICENO) AS AVERAGE_PRODUCTS_PER_ORDER
FROM ONLINE_RETAIL;




-- 17. WHICH PRODUCTS ARE MOST COMMONLY PURCHASED TOGETHER IN THE SAME ORDER?
SELECT 
    A.DESCRIPTION AS PRODUCT_1,
    B.DESCRIPTION AS PRODUCT_2,
    COUNT(*) AS TIMES_BOUGHT_TOGETHER
FROM ONLINE_RETAIL A
JOIN ONLINE_RETAIL B
ON A.INVOICENO = B.INVOICENO
AND A.DESCRIPTION < B.DESCRIPTION
GROUP BY 
    A.DESCRIPTION,
    B.DESCRIPTION
ORDER BY 
    TIMES_BOUGHT_TOGETHER DESC;





-- 18. ARE THERE PRODUCTS THAT GENERATE HIGH REVENUE BUT ARE PURCHASED BY ONLY A FEW CUSTOMERS?
WITH PRODUCT_ACCORDING_TO_REVENUE AS(
SELECT
    DESCRIPTION,
    COUNT(DISTINCT CUSTOMERID) AS CUSTOMER_COUNT,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION)

SELECT 
*
FROM PRODUCT_ACCORDING_TO_REVENUE
WHERE CUSTOMER_COUNT < (SELECT AVG(CUSTOMER_COUNT) FROM PRODUCT_ACCORDING_TO_REVENUE) 
AND 
TOTAL_REVENUE > (SELECT AVG(TOTAL_REVENUE) FROM PRODUCT_ACCORDING_TO_REVENUE);



-- 19. WHICH CUSTOMERS HAVE NOT PURCHASED ANYTHING FOR A LONG TIME AND MAY BE AT RISK OF CHURN?
SELECT
    CUSTOMERID,
    DATEDIFF(DAY, MAX(INVOICEDATE), 
        (SELECT MAX(INVOICEDATE) FROM ONLINE_RETAIL)
    ) AS DAYS_SINCE_LAST_PURCHASE
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
ORDER BY DAYS_SINCE_LAST_PURCHASE DESC;



-- 20. WHICH COUNTRIES HAVE THE HIGHEST AVERAGE SPENDING PER CUSTOMER?
SELECT
    COUNTRY,
    SUM(REVENUE) / COUNT(DISTINCT CUSTOMERID) AS AVG_SPENDING_PER_CUSTOMER
FROM ONLINE_RETAIL
GROUP BY COUNTRY
ORDER BY AVG_SPENDING_PER_CUSTOMER DESC;



-- 21. WHAT PROPORTION OF OUR REVENUE COMES FROM THE TOP-SELLING 20 PRODUCTS?
WITH TOP_TWENTY AS (
    SELECT TOP 20
        DESCRIPTION,
        SUM(REVENUE) AS TOTAL_REVENUE
    FROM ONLINE_RETAIL
    GROUP BY DESCRIPTION
    ORDER BY SUM(REVENUE) DESC
),

TOTAL_REVENUE AS (
    SELECT 
        SUM(REVENUE) AS OVERALL_REVENUE
    FROM ONLINE_RETAIL
)

SELECT
    ROUND(SUM(T.TOTAL_REVENUE) * 100.0 / MAX(TR.OVERALL_REVENUE),2) AS REVENUE_PROPORTION
FROM TOP_TWENTY T
CROSS JOIN TOTAL_REVENUE TR;



-- 22. ARE THERE CUSTOMERS WHO PLACE LARGE ORDERS WITH MANY ITEMS BUT LOW TOTAL REVENUE?
WITH CUSTOMER_METRICS AS (
SELECT 
    CUSTOMERID,
    COUNT(DISTINCT INVOICENO) AS ORDERS_PER_CUSTOMER,
    SUM(QUANTITY) AS TOTAL_ITEMS,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
)

SELECT *
FROM CUSTOMER_METRICS
WHERE TOTAL_ITEMS > (
        SELECT AVG(TOTAL_ITEMS) 
        FROM CUSTOMER_METRICS
      )
AND TOTAL_REVENUE < (
        SELECT AVG(TOTAL_REVENUE) 
        FROM CUSTOMER_METRICS
      );



-- 23. WHICH PRODUCTS GENERATE CONSISTENT SALES EVERY MONTH VERSUS PRODUCTS THAT SELL ONLY OCCASIONALLY?
WITH PRODUCT_MONTHS AS (
SELECT
    DESCRIPTION,
    COUNT(DISTINCT FORMAT(INVOICEDATE,'yyyy-MM')) AS MONTHS_SOLD
FROM ONLINE_RETAIL
GROUP BY DESCRIPTION
)

SELECT
    DESCRIPTION,
    MONTHS_SOLD,
    CASE 
        WHEN MONTHS_SOLD >= 10 THEN 'CONSISTENT SELLER'
        WHEN MONTHS_SOLD BETWEEN 4 AND 9 THEN 'MODERATE SELLER'
        ELSE 'OCCASIONAL SELLER'
    END AS SALES_PATTERN
FROM PRODUCT_MONTHS
ORDER BY MONTHS_SOLD DESC;




-- 24. WHICH CUSTOMERS CONTRIBUTE THE MOST REVENUE RELATIVE TO HOW FREQUENTLY THEY PURCHASE?

WITH CUSTOMER_METRICS AS (
SELECT
    CUSTOMERID,
    COUNT(DISTINCT INVOICENO) AS TOTAL_ORDERS,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM ONLINE_RETAIL
GROUP BY CUSTOMERID
)

SELECT
    CUSTOMERID,
    TOTAL_ORDERS,
    TOTAL_REVENUE,
    TOTAL_REVENUE * 1.0 / TOTAL_ORDERS AS REVENUE_PER_ORDER
FROM CUSTOMER_METRICS
ORDER BY REVENUE_PER_ORDER DESC;




-- Basic KPIs
SELECT
'Total Revenue' AS metric,
Round(SUM(Revenue),2) AS value
FROM online_retail

UNION ALL
 
SELECT
'Total Orders',
COUNT(DISTINCT InvoiceNo)
FROM online_retail

UNION ALL

SELECT
'Total Customers',
COUNT(DISTINCT CustomerID)
FROM online_retail

UNION ALL

SELECT 
'Average Order Value',
Round(SUM(Revenue) * 1.0 / COUNT(DISTINCT InvoiceNo),2)
FROM online_retail;